name: Pull Requests (CI)

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Running jest test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: NPM Install
        run: npm ci
      
      - name: Lint check
        run: npm run lint
      
      - name: Test run with coverage check
        run: npm run coverage

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: coverage
          path: coverage
